name: advanced_ui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/img/icons/
    - assets/img/posts/large/
    - assets/img/posts/small/
    - assets/img/stories/
    - assets/img/background/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_bold.otf
          weight: 200
        - asset: assets/fonts/avenir_regular.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProBlack.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProBlackOblique.otf
          weight: 700
        - asset: assets/fonts/AvenirLTProBook.otf
        - asset: assets/fonts/AvenirLTProBookOblique.otf
        - asset: assets/fonts/AvenirLTProHeavy.otf
        - asset: assets/fonts/AvenirLTProHeavyOblique.otf
        - asset: assets/fonts/AvenirLTProLight.otf
        - asset: assets/fonts/AvenirLTProLightOblique.otf
        - asset: assets/fonts/AvenirLTProMedium.otf
        - asset: assets/fonts/AvenirLTProMediumOblique.otf
        - asset: assets/fonts/AvenirLTProOblique.otf
        - asset: assets/fonts/AvenirLTProRoman.otf

flutter_gen:
  integrations:
    flutter_svg: true